# BIS15L-Project
```{r}
library(tidyverse)
library(shiny)
library(shinydashboard)
library(naniar)
library(lubridate)
library(here)

```

```{r}
#Reading the two CSV
setwd("..")
longitudinal <- readr::read_csv(here('data','oasis_longitudinal.csv'))
cross_sectional <- readr::read_csv(here('data','oasis_cross-sectional.csv'))


#Taking a peek at the data

glimpse(longitudinal)
glimpse(cross_sectional)
```
```{r}
longitudinal %>%
  filter(Group == 'Demented' | Group == 'Converted') %>%
  ggplot(aes(x = SES)) + geom_bar() + labs(title = "Distribution of people with dementia by socio economic status (SES)")



longitudinal %>%
  filter(Group == 'Demented' | Group == 'Converted') %>%
  ggplot(aes(x = Age)) + geom_bar() + labs(title = "Distribution of people with dementia by age")


```

```{r}

n_patients <- longitudinal%>%
  filter(SES==2) %>%
  nrow()
cat(n_patients,"fit listed criteria")

ui <- fluidPage(
    selectInput("SES", "Select Economic Status", choices=unique(longitudinal$SES)),
    selectInput("Age", "Select Age", choices = c("50-60", "60-70", "70-80", "80-90")),
                
  textOutput("result")
  
)



server <- function(input, output, session) {
  
numpatients <-  reactive({longitudinal %>%
    filter(SES==input$SES) %>%
    nrow()
    })

numdemented <-  reactive({longitudinal %>%
    filter(SES==input$SES) %>%
    filter(Group=='Demented') %>%
    nrow()
    })
  
  output$result <- renderText({
    c(numpatients(),"patients meet listed search criteria, out of which", numdemented(), "have dementia or approximately", round((numdemented()/numpatients())*100), "% of the sample")
  })

 
  
  # stop the app when we close it
  session$onSessionEnded(stopApp)
}


shinyApp(ui, server)
  
```


